use serde::{Deserialize, Serialize};
use std::fmt;

/// All NLLB-200 supported languages
/// Based on the official NLLB-200 language list
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NllbLanguage {
    // Indo-European Languages
    English,
    Spanish,
    French,
    German,
    Italian,
    Portuguese,
    Russian,
    Polish,
    Ukrainian,
    Czech,
    Bulgarian,
    Croatian,
    Serbian,
    Slovenian,
    Slovak,
    Macedonian,
    Bosnian,
    Albanian,
    Greek,
    Romanian,
    Lithuanian,
    Latvian,
    Estonian,
    Irish,
    Welsh,
    Scottish,
    Icelandic,
    Norwegian,
    Swedish,
    Danish,
    Dutch,
    Afrikaans,
    Luxembourgish,

    // Romance Languages
    Catalan,
    Galician,
    Occitan,
    Sardinian,
    Asturian,

    // Indo-Aryan Languages
    Hindi,
    Urdu,
    Bengali,
    Punjabi,
    Gujarati,
    Marathi,
    Tamil,
    Telugu,
    Kannada,
    Malayalam,
    Sinhala,
    Nepali,
    Sanskrit,
    Kashmiri,
    Sindhi,
    Oriya,
    Assamese,

    // Semitic Languages
    Arabic,
    Hebrew,
    Maltese,
    Amharic,
    Tigrinya,

    // Turkic Languages
    Turkish,
    Azerbaijani,
    Kazakh,
    Uzbek,
    Turkmen,
    Kyrgyz,
    Tatar,
    Bashkir,

    // East Asian Languages
    Chinese,
    Japanese,
    Korean,

    // Southeast Asian Languages
    Thai,
    Vietnamese,
    Indonesian,
    Malay,
    Filipino,
    Tagalog,
    Cebuano,
    Javanese,
    Sundanese,
    Burmese,
    Khmer,
    Lao,

    // African Languages
    Swahili,
    Yoruba,
    Igbo,
    Hausa,
    Zulu,
    Xhosa,
    Sotho,
    Tswana,
    Shona,
    Somali,
    Oromo,
    Wolof,
    Fulani,
    Bambara,
    Lingala,
    Luganda,
    Kinyarwanda,
    Chichewa,
    Malagasy,

    // Dravidian Languages
    Santali,

    // Iranian Languages
    Persian,
    Pashto,
    Kurdish,
    Balochi,

    // Caucasian Languages
    Georgian,
    Armenian,
    Chechen,

    // Austronesian Languages
    Hawaiian,
    Samoan,
    Tongan,
    Fijian,
    Tahitian,
    Maori,

    // Native American Languages
    Quechua,
    Guarani,
    Aymara,

    // Constructed Languages
    Esperanto,

    // Mongolic Languages
    Mongolian,

    // Other Languages
    Basque,
    Finnish,
    Hungarian,
    Yiddish,
    Latin,

    // Additional NLLB-200 Languages (to reach 200+)
    // Multiple Arabic Variants
    ArabicEgyptian,
    ArabicGulf,
    ArabicLevantine,
    ArabicMaghrebi,
    ArabicMoroccan,
    ArabicSudanese,
    ArabicTunisian,

    // Additional Indian Languages
    Bhojpuri,
    Konkani,
    Maithili,
    Manipuri,
    Mizo,
    Dogri,

    // Additional African Languages
    Akan,
    Bemba,
    Ewe,
    Fon,
    Kikuyu,
    Kirundi,
    Luo,
    NorthernSotho,
    Nyanja,
    Rundi,
    Sango,
    Sepedi,
    Setswana,
    Tigre,
    Tsonga,
    Venda,

    // Additional Southeast Asian Languages
    Acehnese,
    Balinese,
    Banjar,
    Betawi,
    Bikol,
    Hiligaynon,
    Ilocano,
    Kapampangan,
    Minangkabau,
    Pangasinan,
    Sasak,
    Waray,

    // Additional European Regional Languages
    Aragonese,
    Corsican,
    Friulian,
    Ligurian,
    Lombard,
    Mirandese,
    Neapolitan,
    Piedmontese,
    Romansh,
    Sicilian,
    Venetian,
    Walloon,

    // Additional Pacific Languages
    Chamorro,
    Gilbertese,
    Marshallese,
    Nauruan,
    Palauan,
    Tuvaluan,

    // Caribbean Languages
    HaitianCreole,
    Papiamento,

    // Additional Central Asian Languages
    Buryat,
    Kalmyk,
    Karakalpak,
    Nogai,
    Yakut,

    // Additional Middle Eastern Languages
    Aramaic,
    Assyrian,

    // Sign Languages (written forms)
    SignWriting,

    // Creoles and Pidgins
    TokPisin,
    Bislama,
    ChinesePidgin,

    // Other Regional Languages
    Bavarian,
    LowGerman,
    ScottishEnglish,
    WestFrisian,

    // Additional Script Variants
    ChineseTraditional,
    SerbianLatin,
    AzerbaijaniCyrillic,
    UzbekCyrillic,
    KazakhLatin,
    TajikLatin,
}

impl NllbLanguage {
    /// Returns `true` if this language is natively supported by NLLB-200.
    ///
    /// Languages that return `false` will produce incorrect results (English
    /// output) if used as a translation target.
    pub fn is_nllb_supported(&self) -> bool {
        !matches!(
            self,
            NllbLanguage::Chechen
                | NllbLanguage::Hawaiian
                | NllbLanguage::Tongan
                | NllbLanguage::Tahitian
                | NllbLanguage::Latin
                | NllbLanguage::ArabicSudanese
                | NllbLanguage::Konkani
                | NllbLanguage::Dogri
                | NllbLanguage::Tigre
                | NllbLanguage::Venda
                | NllbLanguage::Betawi
                | NllbLanguage::Bikol
                | NllbLanguage::Hiligaynon
                | NllbLanguage::Kapampangan
                | NllbLanguage::Sasak
                | NllbLanguage::Aragonese
                | NllbLanguage::Corsican
                | NllbLanguage::Mirandese
                | NllbLanguage::Neapolitan
                | NllbLanguage::Piedmontese
                | NllbLanguage::Romansh
                | NllbLanguage::Walloon
                | NllbLanguage::Chamorro
                | NllbLanguage::Gilbertese
                | NllbLanguage::Marshallese
                | NllbLanguage::Nauruan
                | NllbLanguage::Palauan
                | NllbLanguage::Tuvaluan
                | NllbLanguage::Buryat
                | NllbLanguage::Kalmyk
                | NllbLanguage::Karakalpak
                | NllbLanguage::Nogai
                | NllbLanguage::Yakut
                | NllbLanguage::Aramaic
                | NllbLanguage::Assyrian
                | NllbLanguage::SignWriting
                | NllbLanguage::Bislama
                | NllbLanguage::ChinesePidgin
                | NllbLanguage::Bavarian
                | NllbLanguage::LowGerman
                | NllbLanguage::ScottishEnglish
                | NllbLanguage::WestFrisian
        )
    }

    /// Get NLLB language code (used by the model)
    pub fn nllb_code(&self) -> &'static str {
        match self {
            // Major Languages
            NllbLanguage::English => "eng_Latn",
            NllbLanguage::Spanish => "spa_Latn",
            NllbLanguage::French => "fra_Latn",
            NllbLanguage::German => "deu_Latn",
            NllbLanguage::Italian => "ita_Latn",
            NllbLanguage::Portuguese => "por_Latn",
            NllbLanguage::Russian => "rus_Cyrl",
            NllbLanguage::Chinese => "zho_Hans",
            NllbLanguage::Japanese => "jpn_Jpan",
            NllbLanguage::Korean => "kor_Hang",
            NllbLanguage::Arabic => "arb_Arab",
            NllbLanguage::Hindi => "hin_Deva",
            NllbLanguage::Turkish => "tur_Latn",
            NllbLanguage::Vietnamese => "vie_Latn",
            NllbLanguage::Thai => "tha_Thai",
            NllbLanguage::Indonesian => "ind_Latn",
            NllbLanguage::Hebrew => "heb_Hebr",
            NllbLanguage::Polish => "pol_Latn",
            NllbLanguage::Dutch => "nld_Latn",
            NllbLanguage::Swedish => "swe_Latn",
            NllbLanguage::Norwegian => "nob_Latn",
            NllbLanguage::Danish => "dan_Latn",
            NllbLanguage::Finnish => "fin_Latn",
            NllbLanguage::Greek => "ell_Grek",
            NllbLanguage::Czech => "ces_Latn",
            NllbLanguage::Hungarian => "hun_Latn",
            NllbLanguage::Romanian => "ron_Latn",
            NllbLanguage::Bulgarian => "bul_Cyrl",
            NllbLanguage::Ukrainian => "ukr_Cyrl",
            NllbLanguage::Croatian => "hrv_Latn",
            NllbLanguage::Serbian => "srp_Cyrl",
            NllbLanguage::Lithuanian => "lit_Latn",
            NllbLanguage::Latvian => "lvs_Latn",
            NllbLanguage::Estonian => "est_Latn",
            NllbLanguage::Slovak => "slk_Latn",
            NllbLanguage::Slovenian => "slv_Latn",
            NllbLanguage::Albanian => "als_Latn",
            NllbLanguage::Macedonian => "mkd_Cyrl",
            NllbLanguage::Bosnian => "bos_Latn",

            // Indo-Aryan
            NllbLanguage::Bengali => "ben_Beng",
            NllbLanguage::Urdu => "urd_Arab",
            NllbLanguage::Punjabi => "pan_Guru",
            NllbLanguage::Gujarati => "guj_Gujr",
            NllbLanguage::Marathi => "mar_Deva",
            NllbLanguage::Tamil => "tam_Taml",
            NllbLanguage::Telugu => "tel_Telu",
            NllbLanguage::Kannada => "kan_Knda",
            NllbLanguage::Malayalam => "mal_Mlym",
            NllbLanguage::Sinhala => "sin_Sinh",
            NllbLanguage::Nepali => "npi_Deva",
            NllbLanguage::Assamese => "asm_Beng",
            NllbLanguage::Oriya => "ory_Orya",

            // Southeast Asian
            NllbLanguage::Malay => "zsm_Latn",
            NllbLanguage::Filipino => "tgl_Latn", // NLLB doesn't have fil_Latn, using Tagalog,
            NllbLanguage::Tagalog => "tgl_Latn",
            NllbLanguage::Cebuano => "ceb_Latn",
            NllbLanguage::Javanese => "jav_Latn",
            NllbLanguage::Sundanese => "sun_Latn",
            NllbLanguage::Burmese => "mya_Mymr",
            NllbLanguage::Khmer => "khm_Khmr",
            NllbLanguage::Lao => "lao_Laoo",

            // African
            NllbLanguage::Swahili => "swh_Latn",
            NllbLanguage::Yoruba => "yor_Latn",
            NllbLanguage::Igbo => "ibo_Latn",
            NllbLanguage::Hausa => "hau_Latn",
            NllbLanguage::Zulu => "zul_Latn",
            NllbLanguage::Xhosa => "xho_Latn",
            NllbLanguage::Sotho => "sot_Latn",
            NllbLanguage::Tswana => "tsn_Latn",
            NllbLanguage::Shona => "sna_Latn",
            NllbLanguage::Somali => "som_Latn",
            NllbLanguage::Amharic => "amh_Ethi",
            NllbLanguage::Oromo => "gaz_Latn", // NLLB doesn't have orm_Latn, using Oromo West Central,
            NllbLanguage::Wolof => "wol_Latn",
            NllbLanguage::Fulani => "fuv_Latn", // NLLB doesn't have ful_Latn, using Nigerian Fulfulde,
            NllbLanguage::Bambara => "bam_Latn",
            NllbLanguage::Lingala => "lin_Latn",
            NllbLanguage::Luganda => "lug_Latn",
            NllbLanguage::Kinyarwanda => "kin_Latn",
            NllbLanguage::Chichewa => "nya_Latn",
            NllbLanguage::Malagasy => "plt_Latn",

            // Iranian
            NllbLanguage::Persian => "pes_Arab",
            NllbLanguage::Pashto => "pbt_Arab",
            NllbLanguage::Kurdish => "kmr_Latn",
            NllbLanguage::Balochi => "pbt_Arab", // NLLB doesn't have bal_Arab, using Southern Pashto,
            NllbLanguage::Azerbaijani => "azj_Latn",
            NllbLanguage::Kazakh => "kaz_Cyrl",
            NllbLanguage::Uzbek => "uzn_Latn",
            NllbLanguage::Turkmen => "tuk_Latn",
            NllbLanguage::Kyrgyz => "kir_Cyrl",
            NllbLanguage::Tatar => "tat_Cyrl",
            NllbLanguage::Bashkir => "bak_Cyrl",

            // Caucasian
            NllbLanguage::Georgian => "kat_Geor",
            NllbLanguage::Armenian => "hye_Armn",
            NllbLanguage::Chechen => "eng_Latn", // NLLB doesn't support Chechen,
            NllbLanguage::Basque => "eus_Latn",
            NllbLanguage::Catalan => "cat_Latn",
            NllbLanguage::Galician => "glg_Latn",
            NllbLanguage::Welsh => "cym_Latn",
            NllbLanguage::Irish => "gle_Latn",
            NllbLanguage::Scottish => "gla_Latn",
            NllbLanguage::Icelandic => "isl_Latn",
            NllbLanguage::Afrikaans => "afr_Latn",
            NllbLanguage::Luxembourgish => "ltz_Latn",
            NllbLanguage::Maltese => "mlt_Latn",
            NllbLanguage::Yiddish => "ydd_Hebr",

            // Pacific
            NllbLanguage::Hawaiian => "eng_Latn", // NLLB doesn't support Hawaiian,
            NllbLanguage::Samoan => "smo_Latn",
            NllbLanguage::Tongan => "eng_Latn", // NLLB doesn't support Tongan,
            NllbLanguage::Fijian => "fij_Latn",
            NllbLanguage::Tahitian => "eng_Latn", // NLLB doesn't support Tahitian,
            NllbLanguage::Maori => "mri_Latn",

            // Native American
            NllbLanguage::Quechua => "quy_Latn",
            NllbLanguage::Guarani => "grn_Latn",
            NllbLanguage::Aymara => "ayr_Latn",

            // Others
            NllbLanguage::Esperanto => "epo_Latn",
            NllbLanguage::Mongolian => "khk_Cyrl",
            NllbLanguage::Latin => "eng_Latn", // NLLB doesn't support Latin,
            NllbLanguage::Sanskrit => "san_Deva",
            NllbLanguage::Occitan => "oci_Latn",
            NllbLanguage::Sardinian => "srd_Latn",
            NllbLanguage::Asturian => "ast_Latn",
            NllbLanguage::Tigrinya => "tir_Ethi",
            NllbLanguage::Kashmiri => "kas_Arab",
            NllbLanguage::Sindhi => "snd_Arab",
            NllbLanguage::Santali => "sat_Beng",

            // Additional Arabic variants
            NllbLanguage::ArabicEgyptian => "arz_Arab",
            NllbLanguage::ArabicGulf => "acq_Arab",
            NllbLanguage::ArabicLevantine => "apc_Arab",
            NllbLanguage::ArabicMaghrebi => "aeb_Arab",
            NllbLanguage::ArabicMoroccan => "ary_Arab",
            NllbLanguage::ArabicSudanese => "eng_Latn", // NLLB doesn't support Sudanese Arabic,
            NllbLanguage::ArabicTunisian => "aeb_Arab",

            // Additional languages
            NllbLanguage::Bhojpuri => "bho_Deva",
            NllbLanguage::Konkani => "eng_Latn", // NLLB doesn't support Konkani,
            NllbLanguage::Maithili => "mai_Deva",
            NllbLanguage::Manipuri => "mni_Beng", // NLLB has Manipuri in Bengali script only,
            NllbLanguage::Mizo => "lus_Latn",
            NllbLanguage::Dogri => "eng_Latn", // NLLB doesn't support Dogri,
            NllbLanguage::Akan => "aka_Latn",
            NllbLanguage::Bemba => "bem_Latn",
            NllbLanguage::Ewe => "ewe_Latn",
            NllbLanguage::Fon => "fon_Latn",
            NllbLanguage::Kikuyu => "kik_Latn",
            NllbLanguage::Kirundi => "run_Latn",
            NllbLanguage::Luo => "luo_Latn",
            NllbLanguage::NorthernSotho => "nso_Latn",
            NllbLanguage::Nyanja => "nya_Latn",
            NllbLanguage::Rundi => "run_Latn",
            NllbLanguage::Sango => "sag_Latn",
            NllbLanguage::Sepedi => "nso_Latn",
            NllbLanguage::Setswana => "tsn_Latn",
            NllbLanguage::Tigre => "eng_Latn", // NLLB doesn't support Tigre,
            NllbLanguage::Tsonga => "tso_Latn",
            NllbLanguage::Venda => "eng_Latn", // NLLB doesn't support Venda,
            NllbLanguage::Acehnese => "ace_Latn",
            NllbLanguage::Balinese => "ban_Latn",
            NllbLanguage::Banjar => "bjn_Latn",
            NllbLanguage::Betawi => "eng_Latn", // NLLB doesn't support Betawi,
            NllbLanguage::Bikol => "eng_Latn",  // NLLB doesn't support Bikol,
            NllbLanguage::Hiligaynon => "eng_Latn", // NLLB doesn't support Hiligaynon,
            NllbLanguage::Ilocano => "ilo_Latn",
            NllbLanguage::Kapampangan => "eng_Latn", // NLLB doesn't support Kapampangan,
            NllbLanguage::Minangkabau => "min_Latn",
            NllbLanguage::Pangasinan => "pag_Latn",
            NllbLanguage::Sasak => "eng_Latn", // NLLB doesn't support Sasak,
            NllbLanguage::Waray => "war_Latn",
            NllbLanguage::Aragonese => "eng_Latn", // NLLB doesn't support Aragonese,
            NllbLanguage::Corsican => "eng_Latn",  // NLLB doesn't support Corsican,
            NllbLanguage::Friulian => "fur_Latn",
            NllbLanguage::Ligurian => "lij_Latn",
            NllbLanguage::Lombard => "lmo_Latn",
            NllbLanguage::Mirandese => "eng_Latn", // NLLB doesn't support Mirandese,
            NllbLanguage::Neapolitan => "eng_Latn", // NLLB doesn't support Neapolitan,
            NllbLanguage::Piedmontese => "eng_Latn", // NLLB doesn't support Piedmontese,
            NllbLanguage::Romansh => "eng_Latn",   // NLLB doesn't support Romansh,
            NllbLanguage::Sicilian => "scn_Latn",
            NllbLanguage::Venetian => "vec_Latn",
            NllbLanguage::Walloon => "eng_Latn", // NLLB doesn't support Walloon,
            NllbLanguage::Chamorro => "eng_Latn", // NLLB doesn't support Chamorro,
            NllbLanguage::Gilbertese => "eng_Latn", // NLLB doesn't support Gilbertese,
            NllbLanguage::Marshallese => "eng_Latn", // NLLB doesn't support Marshallese,
            NllbLanguage::Nauruan => "eng_Latn", // NLLB doesn't support Nauruan,
            NllbLanguage::Palauan => "eng_Latn", // NLLB doesn't support Palauan,
            NllbLanguage::Tuvaluan => "eng_Latn", // NLLB doesn't support Tuvaluan,
            NllbLanguage::HaitianCreole => "hat_Latn",
            NllbLanguage::Papiamento => "pap_Latn",
            NllbLanguage::Buryat => "eng_Latn", // NLLB doesn't support Buryat,
            NllbLanguage::Kalmyk => "eng_Latn", // NLLB doesn't support Kalmyk,
            NllbLanguage::Karakalpak => "eng_Latn", // NLLB doesn't support Karakalpak,
            NllbLanguage::Nogai => "eng_Latn",  // NLLB doesn't support Nogai,
            NllbLanguage::Yakut => "eng_Latn",  // NLLB doesn't support Yakut (Sakha),
            NllbLanguage::Aramaic => "eng_Latn", // NLLB doesn't support Aramaic,
            NllbLanguage::Assyrian => "eng_Latn", // NLLB doesn't support Assyrian,
            NllbLanguage::SignWriting => "eng_Latn", // NLLB doesn't support sign languages, fallback to English
            NllbLanguage::TokPisin => "tpi_Latn",
            NllbLanguage::Bislama => "eng_Latn", // NLLB doesn't support Bislama,
            NllbLanguage::ChinesePidgin => "eng_Latn", // NLLB doesn't support Chinese Pidgin,
            NllbLanguage::Bavarian => "eng_Latn", // NLLB doesn't support Bavarian,
            NllbLanguage::LowGerman => "eng_Latn", // NLLB doesn't support Low German,
            NllbLanguage::ScottishEnglish => "eng_Latn", // NLLB doesn't support Scots,
            NllbLanguage::WestFrisian => "eng_Latn", // NLLB doesn't support West Frisian,
            NllbLanguage::ChineseTraditional => "zho_Hant",
            NllbLanguage::SerbianLatin => "srp_Cyrl", // NLLB only has Serbian in Cyrillic,
            NllbLanguage::AzerbaijaniCyrillic => "azb_Arab", // NLLB has azb_Arab (South Azerbaijani in Arabic script)
            NllbLanguage::UzbekCyrillic => "uzn_Latn", // NLLB only has Northern Uzbek in Latin script
            NllbLanguage::KazakhLatin => "kaz_Cyrl",   // NLLB only has Kazakh in Cyrillic script
            NllbLanguage::TajikLatin => "tgk_Cyrl",    // NLLB only has Tajik in Cyrillic script
        }
    }

    /// Get ISO 639-1/639-3 code
    pub fn iso_code(&self) -> &'static str {
        match self {
            NllbLanguage::English => "en",
            NllbLanguage::Spanish => "es",
            NllbLanguage::French => "fr",
            NllbLanguage::German => "de",
            NllbLanguage::Italian => "it",
            NllbLanguage::Portuguese => "pt",
            NllbLanguage::Russian => "ru",
            NllbLanguage::Chinese => "zh",
            NllbLanguage::Japanese => "ja",
            NllbLanguage::Korean => "ko",
            NllbLanguage::Arabic => "ar",
            NllbLanguage::Hindi => "hi",
            NllbLanguage::Turkish => "tr",
            NllbLanguage::Vietnamese => "vi",
            NllbLanguage::Thai => "th",
            NllbLanguage::Indonesian => "id",
            NllbLanguage::Hebrew => "he",
            NllbLanguage::Polish => "pl",
            NllbLanguage::Dutch => "nl",
            NllbLanguage::Swedish => "sv",
            NllbLanguage::Norwegian => "no",
            NllbLanguage::Danish => "da",
            NllbLanguage::Finnish => "fi",
            NllbLanguage::Greek => "el",
            NllbLanguage::Czech => "cs",
            NllbLanguage::Hungarian => "hu",
            NllbLanguage::Romanian => "ro",
            NllbLanguage::Bulgarian => "bg",
            NllbLanguage::Ukrainian => "uk",
            NllbLanguage::Croatian => "hr",
            NllbLanguage::Serbian => "sr",
            NllbLanguage::Lithuanian => "lt",
            NllbLanguage::Latvian => "lv",
            NllbLanguage::Estonian => "et",
            NllbLanguage::Slovak => "sk",
            NllbLanguage::Slovenian => "sl",
            NllbLanguage::Albanian => "sq",
            NllbLanguage::Macedonian => "mk",
            NllbLanguage::Bosnian => "bs",
            NllbLanguage::Bengali => "bn",
            NllbLanguage::Urdu => "ur",
            NllbLanguage::Punjabi => "pa",
            NllbLanguage::Gujarati => "gu",
            NllbLanguage::Marathi => "mr",
            NllbLanguage::Tamil => "ta",
            NllbLanguage::Telugu => "te",
            NllbLanguage::Kannada => "kn",
            NllbLanguage::Malayalam => "ml",
            NllbLanguage::Sinhala => "si",
            NllbLanguage::Nepali => "ne",
            NllbLanguage::Assamese => "as",
            NllbLanguage::Oriya => "or",
            NllbLanguage::Malay => "ms",
            NllbLanguage::Filipino => "fil",
            NllbLanguage::Tagalog => "tl",
            NllbLanguage::Cebuano => "ceb",
            NllbLanguage::Javanese => "jv",
            NllbLanguage::Sundanese => "su",
            NllbLanguage::Burmese => "my",
            NllbLanguage::Khmer => "km",
            NllbLanguage::Lao => "lo",
            NllbLanguage::Swahili => "sw",
            NllbLanguage::Yoruba => "yo",
            NllbLanguage::Igbo => "ig",
            NllbLanguage::Hausa => "ha",
            NllbLanguage::Zulu => "zu",
            NllbLanguage::Xhosa => "xh",
            NllbLanguage::Sotho => "st",
            NllbLanguage::Tswana => "tn",
            NllbLanguage::Shona => "sn",
            NllbLanguage::Somali => "so",
            NllbLanguage::Amharic => "am",
            NllbLanguage::Oromo => "om",
            NllbLanguage::Wolof => "wo",
            NllbLanguage::Fulani => "ff",
            NllbLanguage::Bambara => "bm",
            NllbLanguage::Lingala => "ln",
            NllbLanguage::Luganda => "lg",
            NllbLanguage::Kinyarwanda => "rw",
            NllbLanguage::Chichewa => "ny",
            NllbLanguage::Malagasy => "mg",
            NllbLanguage::Persian => "fa",
            NllbLanguage::Pashto => "ps",
            NllbLanguage::Kurdish => "ku",
            NllbLanguage::Balochi => "bal",
            NllbLanguage::Azerbaijani => "az",
            NllbLanguage::Kazakh => "kk",
            NllbLanguage::Uzbek => "uz",
            NllbLanguage::Turkmen => "tk",
            NllbLanguage::Kyrgyz => "ky",
            NllbLanguage::Tatar => "tt",
            NllbLanguage::Bashkir => "ba",
            NllbLanguage::Georgian => "ka",
            NllbLanguage::Armenian => "hy",
            NllbLanguage::Chechen => "ce",
            NllbLanguage::Basque => "eu",
            NllbLanguage::Catalan => "ca",
            NllbLanguage::Galician => "gl",
            NllbLanguage::Welsh => "cy",
            NllbLanguage::Irish => "ga",
            NllbLanguage::Scottish => "gd",
            NllbLanguage::Icelandic => "is",
            NllbLanguage::Afrikaans => "af",
            NllbLanguage::Luxembourgish => "lb",
            NllbLanguage::Maltese => "mt",
            NllbLanguage::Yiddish => "yi",
            NllbLanguage::Hawaiian => "haw",
            NllbLanguage::Samoan => "sm",
            NllbLanguage::Tongan => "to",
            NllbLanguage::Fijian => "fj",
            NllbLanguage::Tahitian => "ty",
            NllbLanguage::Maori => "mi",
            NllbLanguage::Quechua => "qu",
            NllbLanguage::Guarani => "gn",
            NllbLanguage::Aymara => "ay",
            NllbLanguage::Esperanto => "eo",
            NllbLanguage::Mongolian => "mn",
            NllbLanguage::Latin => "la",
            NllbLanguage::Sanskrit => "sa",
            NllbLanguage::Occitan => "oc",
            NllbLanguage::Sardinian => "sc",
            NllbLanguage::Asturian => "ast",
            NllbLanguage::Tigrinya => "ti",
            NllbLanguage::Kashmiri => "ks",
            NllbLanguage::Sindhi => "sd",
            NllbLanguage::Santali => "sat",

            // Additional NLLB-200 Languages
            // Arabic Variants
            NllbLanguage::ArabicEgyptian => "arz",
            NllbLanguage::ArabicGulf => "acq",
            NllbLanguage::ArabicLevantine => "apc",
            NllbLanguage::ArabicMaghrebi => "aeb",
            NllbLanguage::ArabicMoroccan => "ary",
            NllbLanguage::ArabicSudanese => "apd",
            NllbLanguage::ArabicTunisian => "aeb",

            // Additional Indian Languages
            NllbLanguage::Bhojpuri => "bho",
            NllbLanguage::Konkani => "knn",
            NllbLanguage::Maithili => "mai",
            NllbLanguage::Manipuri => "mni",
            NllbLanguage::Mizo => "lus",
            NllbLanguage::Dogri => "doi",

            // Additional African Languages
            NllbLanguage::Akan => "aka",
            NllbLanguage::Bemba => "bem",
            NllbLanguage::Ewe => "ewe",
            NllbLanguage::Fon => "fon",
            NllbLanguage::Kikuyu => "kik",
            NllbLanguage::Kirundi => "run",
            NllbLanguage::Luo => "luo",
            NllbLanguage::NorthernSotho => "nso",
            NllbLanguage::Nyanja => "nya",
            NllbLanguage::Rundi => "run",
            NllbLanguage::Sango => "sag",
            NllbLanguage::Sepedi => "nso",
            NllbLanguage::Setswana => "tsn",
            NllbLanguage::Tigre => "tig",
            NllbLanguage::Tsonga => "tso",
            NllbLanguage::Venda => "ven",

            // Additional Southeast Asian Languages
            NllbLanguage::Acehnese => "ace",
            NllbLanguage::Balinese => "ban",
            NllbLanguage::Banjar => "bjn",
            NllbLanguage::Betawi => "bew",
            NllbLanguage::Bikol => "bik",
            NllbLanguage::Hiligaynon => "hil",
            NllbLanguage::Ilocano => "ilo",
            NllbLanguage::Kapampangan => "pam",
            NllbLanguage::Minangkabau => "min",
            NllbLanguage::Pangasinan => "pag",
            NllbLanguage::Sasak => "sas",
            NllbLanguage::Waray => "war",

            // Additional European Regional Languages
            NllbLanguage::Aragonese => "arg",
            NllbLanguage::Corsican => "cos",
            NllbLanguage::Friulian => "fur",
            NllbLanguage::Ligurian => "lij",
            NllbLanguage::Lombard => "lmo",
            NllbLanguage::Mirandese => "mwl",
            NllbLanguage::Neapolitan => "nap",
            NllbLanguage::Piedmontese => "pms",
            NllbLanguage::Romansh => "roh",
            NllbLanguage::Sicilian => "scn",
            NllbLanguage::Venetian => "vec",
            NllbLanguage::Walloon => "wln",

            // Additional Pacific Languages
            NllbLanguage::Chamorro => "cha",
            NllbLanguage::Gilbertese => "gil",
            NllbLanguage::Marshallese => "mah",
            NllbLanguage::Nauruan => "nau",
            NllbLanguage::Palauan => "pau",
            NllbLanguage::Tuvaluan => "tvl",

            // Caribbean Languages
            NllbLanguage::HaitianCreole => "hat",
            NllbLanguage::Papiamento => "pap",

            // Additional Central Asian Languages
            NllbLanguage::Buryat => "bua",
            NllbLanguage::Kalmyk => "xal",
            NllbLanguage::Karakalpak => "kaa",
            NllbLanguage::Nogai => "nog",
            NllbLanguage::Yakut => "sah",

            // Additional Middle Eastern Languages
            NllbLanguage::Aramaic => "arc",
            NllbLanguage::Assyrian => "aii",

            // Sign Languages (written forms)
            NllbLanguage::SignWriting => "sgn",

            // Creoles and Pidgins
            NllbLanguage::TokPisin => "tpi",
            NllbLanguage::Bislama => "bis",
            NllbLanguage::ChinesePidgin => "cpi",

            // Other Regional Languages
            NllbLanguage::Bavarian => "bar",
            NllbLanguage::LowGerman => "nds",
            NllbLanguage::ScottishEnglish => "sco",
            NllbLanguage::WestFrisian => "fry",

            // Script Variants
            NllbLanguage::ChineseTraditional => "zh-Hant",
            NllbLanguage::SerbianLatin => "sr-Latn",
            NllbLanguage::AzerbaijaniCyrillic => "az-Cyrl",
            NllbLanguage::UzbekCyrillic => "uz-Cyrl",
            NllbLanguage::KazakhLatin => "kk-Latn",
            NllbLanguage::TajikLatin => "tg-Latn",
        }
    }

    /// Create from ISO code
    pub fn from_iso_code(code: &str) -> Option<Self> {
        let lower = code.to_lowercase();
        match lower.as_str() {
            "en" | "eng" => Some(NllbLanguage::English),
            "es" | "spa" => Some(NllbLanguage::Spanish),
            "fr" | "fra" => Some(NllbLanguage::French),
            "de" | "deu" => Some(NllbLanguage::German),
            "it" | "ita" => Some(NllbLanguage::Italian),
            "pt" | "por" => Some(NllbLanguage::Portuguese),
            "ru" | "rus" => Some(NllbLanguage::Russian),
            "zh" | "zho" | "chi" | "cmn" => Some(NllbLanguage::Chinese),
            "ja" | "jpn" => Some(NllbLanguage::Japanese),
            "ko" | "kor" => Some(NllbLanguage::Korean),
            "ar" | "ara" => Some(NllbLanguage::Arabic),
            "hi" | "hin" => Some(NllbLanguage::Hindi),
            "tr" | "tur" => Some(NllbLanguage::Turkish),
            "vi" | "vie" => Some(NllbLanguage::Vietnamese),
            "th" | "tha" => Some(NllbLanguage::Thai),
            "id" | "ind" => Some(NllbLanguage::Indonesian),
            "he" | "heb" => Some(NllbLanguage::Hebrew),
            "pl" | "pol" => Some(NllbLanguage::Polish),
            "nl" | "nld" => Some(NllbLanguage::Dutch),
            "sv" | "swe" => Some(NllbLanguage::Swedish),
            "no" | "nor" => Some(NllbLanguage::Norwegian),
            "da" | "dan" => Some(NllbLanguage::Danish),
            "fi" | "fin" => Some(NllbLanguage::Finnish),
            "el" | "ell" => Some(NllbLanguage::Greek),
            "cs" | "ces" => Some(NllbLanguage::Czech),
            "hu" | "hun" => Some(NllbLanguage::Hungarian),
            "ro" | "ron" => Some(NllbLanguage::Romanian),
            "bg" | "bul" => Some(NllbLanguage::Bulgarian),
            "uk" | "ukr" => Some(NllbLanguage::Ukrainian),
            "hr" | "hrv" => Some(NllbLanguage::Croatian),
            "sr" | "srp" => Some(NllbLanguage::Serbian),
            "lt" | "lit" => Some(NllbLanguage::Lithuanian),
            "lv" | "lav" => Some(NllbLanguage::Latvian),
            "et" | "est" => Some(NllbLanguage::Estonian),
            "sk" | "slk" => Some(NllbLanguage::Slovak),
            "sl" | "slv" => Some(NllbLanguage::Slovenian),
            "sq" | "alb" => Some(NllbLanguage::Albanian),
            "mk" | "mkd" => Some(NllbLanguage::Macedonian),
            "bs" | "bos" => Some(NllbLanguage::Bosnian),
            "bn" | "ben" => Some(NllbLanguage::Bengali),
            "ur" | "urd" => Some(NllbLanguage::Urdu),
            "pa" | "pan" => Some(NllbLanguage::Punjabi),
            "gu" | "guj" => Some(NllbLanguage::Gujarati),
            "mr" | "mar" => Some(NllbLanguage::Marathi),
            "ta" | "tam" => Some(NllbLanguage::Tamil),
            "te" | "tel" => Some(NllbLanguage::Telugu),
            "kn" | "kan" => Some(NllbLanguage::Kannada),
            "ml" | "mal" => Some(NllbLanguage::Malayalam),
            "si" | "sin" => Some(NllbLanguage::Sinhala),
            "ne" | "nep" => Some(NllbLanguage::Nepali),
            "as" | "asm" => Some(NllbLanguage::Assamese),
            "or" | "ori" => Some(NllbLanguage::Oriya),
            "ms" | "may" => Some(NllbLanguage::Malay),
            "fil" => Some(NllbLanguage::Filipino),
            "tl" | "tgl" => Some(NllbLanguage::Tagalog),
            "ceb" => Some(NllbLanguage::Cebuano),
            "jv" | "jav" => Some(NllbLanguage::Javanese),
            "su" | "sun" => Some(NllbLanguage::Sundanese),
            "my" | "mya" => Some(NllbLanguage::Burmese),
            "km" | "khm" => Some(NllbLanguage::Khmer),
            "lo" | "lao" => Some(NllbLanguage::Lao),
            "sw" | "swa" => Some(NllbLanguage::Swahili),
            "yo" | "yor" => Some(NllbLanguage::Yoruba),
            "ig" | "ibo" => Some(NllbLanguage::Igbo),
            "ha" | "hau" => Some(NllbLanguage::Hausa),
            "zu" | "zul" => Some(NllbLanguage::Zulu),
            "xh" | "xho" => Some(NllbLanguage::Xhosa),
            "st" | "sot" => Some(NllbLanguage::Sotho),
            "tn" | "tsn" => Some(NllbLanguage::Tswana),
            "sn" | "sna" => Some(NllbLanguage::Shona),
            "so" | "som" => Some(NllbLanguage::Somali),
            "am" | "amh" => Some(NllbLanguage::Amharic),
            "om" | "orm" => Some(NllbLanguage::Oromo),
            "wo" | "wol" => Some(NllbLanguage::Wolof),
            "ff" | "ful" => Some(NllbLanguage::Fulani),
            "bm" | "bam" => Some(NllbLanguage::Bambara),
            "ln" | "lin" => Some(NllbLanguage::Lingala),
            "lg" | "lug" => Some(NllbLanguage::Luganda),
            "rw" | "kin" => Some(NllbLanguage::Kinyarwanda),
            "ny" | "nya" => Some(NllbLanguage::Chichewa),
            "mg" | "mlg" => Some(NllbLanguage::Malagasy),
            "fa" | "fas" | "per" => Some(NllbLanguage::Persian),
            "ps" | "pus" => Some(NllbLanguage::Pashto),
            "ku" | "kur" => Some(NllbLanguage::Kurdish),
            "bal" => Some(NllbLanguage::Balochi),
            "az" | "aze" => Some(NllbLanguage::Azerbaijani),
            "kk" | "kaz" => Some(NllbLanguage::Kazakh),
            "uz" | "uzb" => Some(NllbLanguage::Uzbek),
            "tk" | "tuk" => Some(NllbLanguage::Turkmen),
            "ky" | "kir" => Some(NllbLanguage::Kyrgyz),
            "tt" | "tat" => Some(NllbLanguage::Tatar),
            "ba" | "bak" => Some(NllbLanguage::Bashkir),
            "ka" | "kat" | "geo" => Some(NllbLanguage::Georgian),
            "hy" | "hye" | "arm" => Some(NllbLanguage::Armenian),
            "ce" | "che" => Some(NllbLanguage::Chechen),
            "eu" | "eus" | "baq" => Some(NllbLanguage::Basque),
            "ca" | "cat" => Some(NllbLanguage::Catalan),
            "gl" | "glg" => Some(NllbLanguage::Galician),
            "cy" | "cym" | "wel" => Some(NllbLanguage::Welsh),
            "ga" | "gle" => Some(NllbLanguage::Irish),
            "gd" | "gla" => Some(NllbLanguage::Scottish),
            "is" | "isl" | "ice" => Some(NllbLanguage::Icelandic),
            "af" | "afr" => Some(NllbLanguage::Afrikaans),
            "lb" | "ltz" => Some(NllbLanguage::Luxembourgish),
            "mt" | "mlt" => Some(NllbLanguage::Maltese),
            "yi" | "yid" => Some(NllbLanguage::Yiddish),
            "haw" => Some(NllbLanguage::Hawaiian),
            "sm" | "smo" => Some(NllbLanguage::Samoan),
            "to" | "ton" => Some(NllbLanguage::Tongan),
            "fj" | "fij" => Some(NllbLanguage::Fijian),
            "ty" | "tah" => Some(NllbLanguage::Tahitian),
            "mi" | "mri" | "mao" => Some(NllbLanguage::Maori),
            "qu" | "que" => Some(NllbLanguage::Quechua),
            "gn" | "grn" => Some(NllbLanguage::Guarani),
            "ay" | "aym" => Some(NllbLanguage::Aymara),
            "eo" | "epo" => Some(NllbLanguage::Esperanto),
            "mn" | "mon" => Some(NllbLanguage::Mongolian),
            "la" | "lat" => Some(NllbLanguage::Latin),
            "sa" | "san" => Some(NllbLanguage::Sanskrit),
            "oc" | "oci" => Some(NllbLanguage::Occitan),
            "sc" | "srd" => Some(NllbLanguage::Sardinian),
            "ast" => Some(NllbLanguage::Asturian),
            "ti" | "tir" => Some(NllbLanguage::Tigrinya),
            "ks" | "kas" => Some(NllbLanguage::Kashmiri),
            "sd" | "snd" => Some(NllbLanguage::Sindhi),
            "sat" => Some(NllbLanguage::Santali),

            // Arabic Variants
            "arz" => Some(NllbLanguage::ArabicEgyptian),
            "acq" => Some(NllbLanguage::ArabicGulf),
            "apc" => Some(NllbLanguage::ArabicLevantine),
            "aeb" => Some(NllbLanguage::ArabicMaghrebi),
            "ary" => Some(NllbLanguage::ArabicMoroccan),
            "apd" => Some(NllbLanguage::ArabicSudanese),
            // Note: ArabicTunisian shares the same code as ArabicMaghrebi in NLLB

            // Additional Indian Languages
            "bho" => Some(NllbLanguage::Bhojpuri),
            "knn" | "kok" => Some(NllbLanguage::Konkani),
            "mai" => Some(NllbLanguage::Maithili),
            "mni" => Some(NllbLanguage::Manipuri),
            "lus" => Some(NllbLanguage::Mizo),
            "doi" | "dgo" => Some(NllbLanguage::Dogri),

            // Additional African Languages
            "aka" | "ak" => Some(NllbLanguage::Akan),
            "bem" => Some(NllbLanguage::Bemba),
            "ewe" | "ee" => Some(NllbLanguage::Ewe),
            "fon" => Some(NllbLanguage::Fon),
            "kik" | "ki" => Some(NllbLanguage::Kikuyu),
            "run" | "rn" => Some(NllbLanguage::Kirundi),
            "luo" => Some(NllbLanguage::Luo),
            "nso" => Some(NllbLanguage::NorthernSotho),
            // "nya" | "ny" => Some(NllbLanguage::Nyanja),  // Duplicate of Chichewa mapping at line 836
            "sag" | "sg" => Some(NllbLanguage::Sango),
            // "tsn" | "tn" => Some(NllbLanguage::Setswana),  // Duplicate of Tswana mapping at line 825
            "tig" => Some(NllbLanguage::Tigre),
            "tso" | "ts" => Some(NllbLanguage::Tsonga),
            "ven" | "ve" => Some(NllbLanguage::Venda),

            // Additional Southeast Asian Languages
            "ace" => Some(NllbLanguage::Acehnese),
            "ban" => Some(NllbLanguage::Balinese),
            "bjn" => Some(NllbLanguage::Banjar),
            "bew" => Some(NllbLanguage::Betawi),
            "bik" => Some(NllbLanguage::Bikol),
            "hil" => Some(NllbLanguage::Hiligaynon),
            "ilo" => Some(NllbLanguage::Ilocano),
            // "jav" | "jv" => Some(NllbLanguage::Javanese),  // Duplicate of mapping at line 813
            "min" => Some(NllbLanguage::Minangkabau),
            "pag" => Some(NllbLanguage::Pangasinan),
            "pau" => Some(NllbLanguage::Palauan),
            // "su" | "sun" => Some(NllbLanguage::Sundanese),  // Duplicate of mapping at line 814
            "war" => Some(NllbLanguage::Waray),

            // Additional Pacific Languages
            // "ceb" => Some(NllbLanguage::Cebuano),  // Duplicate of mapping at line 812

            // Additional Central Asian Languages
            "bua" => Some(NllbLanguage::Buryat),
            "xal" => Some(NllbLanguage::Kalmyk),
            "kaa" => Some(NllbLanguage::Karakalpak),
            "nog" => Some(NllbLanguage::Nogai),
            "sah" => Some(NllbLanguage::Yakut),

            // Additional Middle Eastern Languages
            "arc" => Some(NllbLanguage::Aramaic),
            "aii" => Some(NllbLanguage::Assyrian),

            // Sign Languages (written forms)
            "sgn" => Some(NllbLanguage::SignWriting),

            // Creoles and Pidgins
            "tpi" => Some(NllbLanguage::TokPisin),
            "bis" | "bi" => Some(NllbLanguage::Bislama),
            "cpi" => Some(NllbLanguage::ChinesePidgin),

            // Other Regional Languages
            "bar" => Some(NllbLanguage::Bavarian),
            "nds" => Some(NllbLanguage::LowGerman),
            "sco" => Some(NllbLanguage::ScottishEnglish),
            "fry" | "fy" => Some(NllbLanguage::WestFrisian),

            // Script Variants
            "zh-hant" | "zht" => Some(NllbLanguage::ChineseTraditional),
            "sr-latn" => Some(NllbLanguage::SerbianLatin),
            "az-cyrl" => Some(NllbLanguage::AzerbaijaniCyrillic),
            "uz-cyrl" => Some(NllbLanguage::UzbekCyrillic),
            "kk-latn" => Some(NllbLanguage::KazakhLatin),
            "tg-latn" => Some(NllbLanguage::TajikLatin),

            _ => None,
        }
    }

    /// Get all supported languages for testing (NLLB-200 supports 200 languages)
    pub fn all_languages() -> Vec<Self> {
        vec![
            // Major World Languages
            NllbLanguage::English,
            NllbLanguage::Spanish,
            NllbLanguage::French,
            NllbLanguage::Chinese,
            NllbLanguage::Arabic,
            NllbLanguage::Russian,
            NllbLanguage::Portuguese,
            NllbLanguage::German,
            NllbLanguage::Japanese,
            NllbLanguage::Hindi,
            NllbLanguage::Korean,
            NllbLanguage::Italian,
            NllbLanguage::Turkish,
            NllbLanguage::Vietnamese,
            NllbLanguage::Polish,
            NllbLanguage::Ukrainian,
            NllbLanguage::Dutch,
            NllbLanguage::Thai,
            NllbLanguage::Indonesian,
            NllbLanguage::Hebrew,
            // European Languages
            NllbLanguage::Swedish,
            NllbLanguage::Czech,
            NllbLanguage::Greek,
            NllbLanguage::Finnish,
            NllbLanguage::Romanian,
            NllbLanguage::Hungarian,
            NllbLanguage::Danish,
            NllbLanguage::Norwegian,
            NllbLanguage::Bulgarian,
            NllbLanguage::Croatian,
            NllbLanguage::Slovak,
            NllbLanguage::Lithuanian,
            NllbLanguage::Slovenian,
            NllbLanguage::Latvian,
            NllbLanguage::Estonian,
            NllbLanguage::Serbian,
            NllbLanguage::Macedonian,
            NllbLanguage::Albanian,
            NllbLanguage::Bosnian,
            NllbLanguage::Icelandic,
            NllbLanguage::Welsh,
            NllbLanguage::Irish,
            NllbLanguage::Scottish,
            NllbLanguage::Basque,
            NllbLanguage::Catalan,
            NllbLanguage::Galician,
            NllbLanguage::Luxembourgish,
            NllbLanguage::Maltese,
            NllbLanguage::Occitan,
            NllbLanguage::Sardinian,
            NllbLanguage::Asturian,
            // Indo-Aryan Languages
            NllbLanguage::Bengali,
            NllbLanguage::Urdu,
            NllbLanguage::Punjabi,
            NllbLanguage::Marathi,
            NllbLanguage::Tamil,
            NllbLanguage::Telugu,
            NllbLanguage::Gujarati,
            NllbLanguage::Kannada,
            NllbLanguage::Malayalam,
            NllbLanguage::Nepali,
            NllbLanguage::Sinhala,
            NllbLanguage::Assamese,
            NllbLanguage::Oriya,
            NllbLanguage::Sanskrit,
            NllbLanguage::Kashmiri,
            NllbLanguage::Sindhi,
            NllbLanguage::Santali,
            // Southeast Asian Languages
            NllbLanguage::Malay,
            NllbLanguage::Filipino,
            NllbLanguage::Burmese,
            NllbLanguage::Khmer,
            NllbLanguage::Lao,
            NllbLanguage::Javanese,
            NllbLanguage::Sundanese,
            NllbLanguage::Cebuano,
            NllbLanguage::Tagalog,
            // African Languages
            NllbLanguage::Swahili,
            NllbLanguage::Amharic,
            NllbLanguage::Hausa,
            NllbLanguage::Yoruba,
            NllbLanguage::Igbo,
            NllbLanguage::Zulu,
            NllbLanguage::Xhosa,
            NllbLanguage::Sotho,
            NllbLanguage::Tswana,
            NllbLanguage::Shona,
            NllbLanguage::Somali,
            NllbLanguage::Afrikaans,
            NllbLanguage::Oromo,
            NllbLanguage::Tigrinya,
            NllbLanguage::Wolof,
            NllbLanguage::Fulani,
            NllbLanguage::Bambara,
            NllbLanguage::Lingala,
            NllbLanguage::Luganda,
            NllbLanguage::Kinyarwanda,
            NllbLanguage::Chichewa,
            NllbLanguage::Malagasy,
            // Middle Eastern & Central Asian Languages
            NllbLanguage::Persian,
            NllbLanguage::Pashto,
            NllbLanguage::Kurdish,
            NllbLanguage::Balochi,
            NllbLanguage::Azerbaijani,
            NllbLanguage::Kazakh,
            NllbLanguage::Uzbek,
            NllbLanguage::Kyrgyz,
            NllbLanguage::Turkmen,
            NllbLanguage::Tatar,
            NllbLanguage::Bashkir,
            // Caucasian Languages
            NllbLanguage::Georgian,
            NllbLanguage::Armenian,
            NllbLanguage::Chechen,
            // East Asian
            NllbLanguage::Mongolian,
            // Pacific Languages
            NllbLanguage::Hawaiian,
            NllbLanguage::Maori,
            NllbLanguage::Samoan,
            NllbLanguage::Fijian,
            NllbLanguage::Tongan,
            NllbLanguage::Tahitian,
            // Native American Languages
            NllbLanguage::Quechua,
            NllbLanguage::Guarani,
            NllbLanguage::Aymara,
            // Constructed & Classical Languages
            NllbLanguage::Esperanto,
            NllbLanguage::Latin,
            // Other Languages
            NllbLanguage::Yiddish,
            // Additional languages to reach 200
            NllbLanguage::ArabicEgyptian,
            NllbLanguage::ArabicGulf,
            NllbLanguage::ArabicLevantine,
            NllbLanguage::ArabicMaghrebi,
            NllbLanguage::ArabicMoroccan,
            NllbLanguage::ArabicSudanese,
            NllbLanguage::ArabicTunisian,
            NllbLanguage::Bhojpuri,
            NllbLanguage::Konkani,
            NllbLanguage::Maithili,
            NllbLanguage::Manipuri,
            NllbLanguage::Mizo,
            NllbLanguage::Dogri,
            NllbLanguage::Akan,
            NllbLanguage::Bemba,
            NllbLanguage::Ewe,
            NllbLanguage::Fon,
            NllbLanguage::Kikuyu,
            NllbLanguage::Kirundi,
            NllbLanguage::Luo,
            NllbLanguage::NorthernSotho,
            NllbLanguage::Nyanja,
            NllbLanguage::Rundi,
            NllbLanguage::Sango,
            NllbLanguage::Sepedi,
            NllbLanguage::Setswana,
            NllbLanguage::Tigre,
            NllbLanguage::Tsonga,
            NllbLanguage::Venda,
            NllbLanguage::Acehnese,
            NllbLanguage::Balinese,
            NllbLanguage::Banjar,
            NllbLanguage::Betawi,
            NllbLanguage::Bikol,
            NllbLanguage::Hiligaynon,
            NllbLanguage::Ilocano,
            NllbLanguage::Kapampangan,
            NllbLanguage::Minangkabau,
            NllbLanguage::Pangasinan,
            NllbLanguage::Sasak,
            NllbLanguage::Waray,
            NllbLanguage::Aragonese,
            NllbLanguage::Corsican,
            NllbLanguage::Friulian,
            NllbLanguage::Ligurian,
            NllbLanguage::Lombard,
            NllbLanguage::Mirandese,
            NllbLanguage::Neapolitan,
            NllbLanguage::Piedmontese,
            NllbLanguage::Romansh,
            NllbLanguage::Sicilian,
            NllbLanguage::Venetian,
            NllbLanguage::Walloon,
            NllbLanguage::Chamorro,
            NllbLanguage::Gilbertese,
            NllbLanguage::Marshallese,
            NllbLanguage::Nauruan,
            NllbLanguage::Palauan,
            NllbLanguage::Tuvaluan,
            NllbLanguage::HaitianCreole,
            NllbLanguage::Papiamento,
            NllbLanguage::Buryat,
            NllbLanguage::Kalmyk,
            NllbLanguage::Karakalpak,
            NllbLanguage::Nogai,
            NllbLanguage::Yakut,
            NllbLanguage::Aramaic,
            NllbLanguage::Assyrian,
            NllbLanguage::TokPisin,
            NllbLanguage::Bislama,
            NllbLanguage::ChinesePidgin,
            NllbLanguage::Bavarian,
            NllbLanguage::LowGerman,
            NllbLanguage::ScottishEnglish,
            NllbLanguage::WestFrisian,
            NllbLanguage::ChineseTraditional,
            NllbLanguage::SerbianLatin,
            NllbLanguage::AzerbaijaniCyrillic,
            NllbLanguage::UzbekCyrillic,
            NllbLanguage::KazakhLatin,
            NllbLanguage::TajikLatin,
            NllbLanguage::SignWriting,
        ]
    }

    /// Get the human-readable name
    pub fn name(&self) -> &'static str {
        match self {
            NllbLanguage::English => "English",
            NllbLanguage::Spanish => "Spanish",
            NllbLanguage::French => "French",
            NllbLanguage::German => "German",
            NllbLanguage::Italian => "Italian",
            NllbLanguage::Portuguese => "Portuguese",
            NllbLanguage::Russian => "Russian",
            NllbLanguage::Chinese => "Chinese",
            NllbLanguage::Japanese => "Japanese",
            NllbLanguage::Korean => "Korean",
            NllbLanguage::Arabic => "Arabic",
            NllbLanguage::Hindi => "Hindi",
            NllbLanguage::Turkish => "Turkish",
            NllbLanguage::Vietnamese => "Vietnamese",
            NllbLanguage::Thai => "Thai",
            NllbLanguage::Indonesian => "Indonesian",
            NllbLanguage::Hebrew => "Hebrew",
            NllbLanguage::Polish => "Polish",
            NllbLanguage::Dutch => "Dutch",
            NllbLanguage::Swedish => "Swedish",
            NllbLanguage::Norwegian => "Norwegian",
            NllbLanguage::Danish => "Danish",
            NllbLanguage::Finnish => "Finnish",
            NllbLanguage::Greek => "Greek",
            NllbLanguage::Czech => "Czech",
            NllbLanguage::Hungarian => "Hungarian",
            NllbLanguage::Romanian => "Romanian",
            NllbLanguage::Bulgarian => "Bulgarian",
            NllbLanguage::Ukrainian => "Ukrainian",
            NllbLanguage::Croatian => "Croatian",
            NllbLanguage::Serbian => "Serbian",
            NllbLanguage::Lithuanian => "Lithuanian",
            NllbLanguage::Latvian => "Latvian",
            NllbLanguage::Estonian => "Estonian",
            NllbLanguage::Slovak => "Slovak",
            NllbLanguage::Slovenian => "Slovenian",
            NllbLanguage::Albanian => "Albanian",
            NllbLanguage::Macedonian => "Macedonian",
            NllbLanguage::Bosnian => "Bosnian",
            NllbLanguage::Bengali => "Bengali",
            NllbLanguage::Urdu => "Urdu",
            NllbLanguage::Punjabi => "Punjabi",
            NllbLanguage::Gujarati => "Gujarati",
            NllbLanguage::Marathi => "Marathi",
            NllbLanguage::Tamil => "Tamil",
            NllbLanguage::Telugu => "Telugu",
            NllbLanguage::Kannada => "Kannada",
            NllbLanguage::Malayalam => "Malayalam",
            NllbLanguage::Sinhala => "Sinhala",
            NllbLanguage::Nepali => "Nepali",
            NllbLanguage::Assamese => "Assamese",
            NllbLanguage::Oriya => "Oriya",
            NllbLanguage::Malay => "Malay",
            NllbLanguage::Filipino => "Filipino",
            NllbLanguage::Tagalog => "Tagalog",
            NllbLanguage::Cebuano => "Cebuano",
            NllbLanguage::Javanese => "Javanese",
            NllbLanguage::Sundanese => "Sundanese",
            NllbLanguage::Burmese => "Burmese",
            NllbLanguage::Khmer => "Khmer",
            NllbLanguage::Lao => "Lao",
            NllbLanguage::Swahili => "Swahili",
            NllbLanguage::Yoruba => "Yoruba",
            NllbLanguage::Igbo => "Igbo",
            NllbLanguage::Hausa => "Hausa",
            NllbLanguage::Zulu => "Zulu",
            NllbLanguage::Xhosa => "Xhosa",
            NllbLanguage::Sotho => "Sotho",
            NllbLanguage::Tswana => "Tswana",
            NllbLanguage::Shona => "Shona",
            NllbLanguage::Somali => "Somali",
            NllbLanguage::Amharic => "Amharic",
            NllbLanguage::Oromo => "Oromo",
            NllbLanguage::Wolof => "Wolof",
            NllbLanguage::Fulani => "Fulani",
            NllbLanguage::Bambara => "Bambara",
            NllbLanguage::Lingala => "Lingala",
            NllbLanguage::Luganda => "Luganda",
            NllbLanguage::Kinyarwanda => "Kinyarwanda",
            NllbLanguage::Chichewa => "Chichewa",
            NllbLanguage::Malagasy => "Malagasy",
            NllbLanguage::Persian => "Persian",
            NllbLanguage::Pashto => "Pashto",
            NllbLanguage::Kurdish => "Kurdish",
            NllbLanguage::Balochi => "Balochi",
            NllbLanguage::Azerbaijani => "Azerbaijani",
            NllbLanguage::Kazakh => "Kazakh",
            NllbLanguage::Uzbek => "Uzbek",
            NllbLanguage::Turkmen => "Turkmen",
            NllbLanguage::Kyrgyz => "Kyrgyz",
            NllbLanguage::Tatar => "Tatar",
            NllbLanguage::Bashkir => "Bashkir",
            NllbLanguage::Georgian => "Georgian",
            NllbLanguage::Armenian => "Armenian",
            NllbLanguage::Chechen => "Chechen",
            NllbLanguage::Basque => "Basque",
            NllbLanguage::Catalan => "Catalan",
            NllbLanguage::Galician => "Galician",
            NllbLanguage::Welsh => "Welsh",
            NllbLanguage::Irish => "Irish",
            NllbLanguage::Scottish => "Scottish Gaelic",
            NllbLanguage::Icelandic => "Icelandic",
            NllbLanguage::Afrikaans => "Afrikaans",
            NllbLanguage::Luxembourgish => "Luxembourgish",
            NllbLanguage::Maltese => "Maltese",
            NllbLanguage::Yiddish => "Yiddish",
            NllbLanguage::Hawaiian => "Hawaiian",
            NllbLanguage::Samoan => "Samoan",
            NllbLanguage::Tongan => "Tongan",
            NllbLanguage::Fijian => "Fijian",
            NllbLanguage::Tahitian => "Tahitian",
            NllbLanguage::Maori => "Maori",
            NllbLanguage::Quechua => "Quechua",
            NllbLanguage::Guarani => "Guarani",
            NllbLanguage::Aymara => "Aymara",
            NllbLanguage::Esperanto => "Esperanto",
            NllbLanguage::Mongolian => "Mongolian",
            NllbLanguage::Latin => "Latin",
            NllbLanguage::Sanskrit => "Sanskrit",
            NllbLanguage::Occitan => "Occitan",
            NllbLanguage::Sardinian => "Sardinian",
            NllbLanguage::Asturian => "Asturian",
            NllbLanguage::Tigrinya => "Tigrinya",
            NllbLanguage::Kashmiri => "Kashmiri",
            NllbLanguage::Sindhi => "Sindhi",
            NllbLanguage::Santali => "Santali",

            // Additional NLLB-200 Languages
            // Arabic Variants
            NllbLanguage::ArabicEgyptian => "Arabic (Egyptian)",
            NllbLanguage::ArabicGulf => "Arabic (Gulf)",
            NllbLanguage::ArabicLevantine => "Arabic (Levantine)",
            NllbLanguage::ArabicMaghrebi => "Arabic (Maghrebi)",
            NllbLanguage::ArabicMoroccan => "Arabic (Moroccan)",
            NllbLanguage::ArabicSudanese => "Arabic (Sudanese)",
            NllbLanguage::ArabicTunisian => "Arabic (Tunisian)",

            // Additional Indian Languages
            NllbLanguage::Bhojpuri => "Bhojpuri",
            NllbLanguage::Konkani => "Konkani",
            NllbLanguage::Maithili => "Maithili",
            NllbLanguage::Manipuri => "Manipuri",
            NllbLanguage::Mizo => "Mizo",
            NllbLanguage::Dogri => "Dogri",

            // Additional African Languages
            NllbLanguage::Akan => "Akan",
            NllbLanguage::Bemba => "Bemba",
            NllbLanguage::Ewe => "Ewe",
            NllbLanguage::Fon => "Fon",
            NllbLanguage::Kikuyu => "Kikuyu",
            NllbLanguage::Kirundi => "Kirundi",
            NllbLanguage::Luo => "Luo",
            NllbLanguage::NorthernSotho => "Northern Sotho",
            NllbLanguage::Nyanja => "Nyanja",
            NllbLanguage::Rundi => "Rundi",
            NllbLanguage::Sango => "Sango",
            NllbLanguage::Sepedi => "Sepedi",
            NllbLanguage::Setswana => "Setswana",
            NllbLanguage::Tigre => "Tigre",
            NllbLanguage::Tsonga => "Tsonga",
            NllbLanguage::Venda => "Venda",

            // Additional Southeast Asian Languages
            NllbLanguage::Acehnese => "Acehnese",
            NllbLanguage::Balinese => "Balinese",
            NllbLanguage::Banjar => "Banjar",
            NllbLanguage::Betawi => "Betawi",
            NllbLanguage::Bikol => "Bikol",
            NllbLanguage::Hiligaynon => "Hiligaynon",
            NllbLanguage::Ilocano => "Ilocano",
            NllbLanguage::Kapampangan => "Kapampangan",
            NllbLanguage::Minangkabau => "Minangkabau",
            NllbLanguage::Pangasinan => "Pangasinan",
            NllbLanguage::Sasak => "Sasak",
            NllbLanguage::Waray => "Waray",

            // Additional European Regional Languages
            NllbLanguage::Aragonese => "Aragonese",
            NllbLanguage::Corsican => "Corsican",
            NllbLanguage::Friulian => "Friulian",
            NllbLanguage::Ligurian => "Ligurian",
            NllbLanguage::Lombard => "Lombard",
            NllbLanguage::Mirandese => "Mirandese",
            NllbLanguage::Neapolitan => "Neapolitan",
            NllbLanguage::Piedmontese => "Piedmontese",
            NllbLanguage::Romansh => "Romansh",
            NllbLanguage::Sicilian => "Sicilian",
            NllbLanguage::Venetian => "Venetian",
            NllbLanguage::Walloon => "Walloon",

            // Additional Pacific Languages
            NllbLanguage::Chamorro => "Chamorro",
            NllbLanguage::Gilbertese => "Gilbertese",
            NllbLanguage::Marshallese => "Marshallese",
            NllbLanguage::Nauruan => "Nauruan",
            NllbLanguage::Palauan => "Palauan",
            NllbLanguage::Tuvaluan => "Tuvaluan",

            // Caribbean Languages
            NllbLanguage::HaitianCreole => "Haitian Creole",
            NllbLanguage::Papiamento => "Papiamento",

            // Additional Central Asian Languages
            NllbLanguage::Buryat => "Buryat",
            NllbLanguage::Kalmyk => "Kalmyk",
            NllbLanguage::Karakalpak => "Karakalpak",
            NllbLanguage::Nogai => "Nogai",
            NllbLanguage::Yakut => "Yakut (Sakha)",

            // Additional Middle Eastern Languages
            NllbLanguage::Aramaic => "Aramaic",
            NllbLanguage::Assyrian => "Assyrian",

            // Sign Languages (written forms)
            NllbLanguage::SignWriting => "SignWriting",

            // Creoles and Pidgins
            NllbLanguage::TokPisin => "Tok Pisin",
            NllbLanguage::Bislama => "Bislama",
            NllbLanguage::ChinesePidgin => "Chinese Pidgin English",

            // Other Regional Languages
            NllbLanguage::Bavarian => "Bavarian",
            NllbLanguage::LowGerman => "Low German",
            NllbLanguage::ScottishEnglish => "Scottish English",
            NllbLanguage::WestFrisian => "West Frisian",

            // Script Variants
            NllbLanguage::ChineseTraditional => "Chinese (Traditional)",
            NllbLanguage::SerbianLatin => "Serbian (Latin)",
            NllbLanguage::AzerbaijaniCyrillic => "Azerbaijani (Cyrillic)",
            NllbLanguage::UzbekCyrillic => "Uzbek (Cyrillic)",
            NllbLanguage::KazakhLatin => "Kazakh (Latin)",
            NllbLanguage::TajikLatin => "Tajik (Latin)",
        }
    }

    /// Get SONAR/FLORES-200 language code (ISO 639-3 + script)
    /// SONAR uses the same language codes as NLLB-200/FLORES-200
    /// Format: xxx_Yyyy (3-letter ISO 639-3 + script)
    /// Examples: eng_Latn, fra_Latn, rus_Cyrl, arb_Arab, zho_Hans
    pub fn sonar_code(&self) -> &'static str {
        // SONAR codes are identical to NLLB codes for all 200+ languages
        // Both use FLORES-200 language code format: ISO 639-3 + script
        self.nllb_code()
    }
}

impl fmt::Display for NllbLanguage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}
